name: publishPackage
on:
  push:
    tags:
      - v*
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v5.0.0
      - name: setupBun
        uses: oven-sh/setup-bun@v2.0.2
        with:
          bun-version: latest
      - name: install
        run: bun install --frozen-lockfile
      - name: check
        run: bun run check
      - name: publish
        run: bun publish
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.npmToken }}
